defaults:
  app:
    publishMetaData:              !env:bool PUBLISH_METADATA
    exchangePrefix:               v1/

    # Component property in the responseTime and process statistics
    statsComponent:               cloud-mirror

    ensureSSL: false
    redirectLimit: 20
    maxWaitForCachedCopy: 28000 #ms
    allowedPatterns:
      - '^https://www\.mozilla\.org/'
      - '^https://s3-us-west-2\.amazonaws\.com/taskcluster-public-artifacts/'
      - '^https://s3\.us-west-2\.amazonaws\.com/taskcluster-public-artifacts/'
      - '^https://public-artifacts\.taskcluster\.net/'
      - '^https://taskcluster-artifacts\.net/'
      - '^https://queue\.taskcluster\.net/'

  taskcluster:
    authBaseUrl: https://auth.taskcluster.net/v1
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  monitoring:
    project: !env MONITORING_PROJECT
    enable: !env:bool MONITORING_ENABLE

  server:
    port: !env:number PORT
    publicUrl: !env PUBLIC_URL
    env: !env NODE_ENV
    forceSSL: !env:flag FORCE_SSL
    trustProxy: false

  backend:
    count: 100
    s3:
      regions: 'us-west-1,us-east-1,us-east-2,eu-central-1,us-west-2'
      acl: 'public-read'
      bucketBase: 'cloud-mirror-' # bucketName = bucketBase + profile + '-' + region
      lifespan: 1 # in days, how long should S3 keep this
      partSize: 33554432 # 32mb
      queueSize: 4
    cacheTTL: 84600 # 23.5 hours

  redis:
    url: !env REDIS

  sqs:
    accessKeyId: !env AWS_ACCESS_KEY_ID
    secretAccessKey: !env AWS_SECRET_ACCESS_KEY
    region: us-west-2
    apiVersion: 2012-11-05

  sqsSimple:
    queueName: !env CLOUD_MIRROR_QUEUE_NAME
    maxReceiveCount: 5
    visibilityTimeout: 600
    deadLetterSuffix: "_dead"

  # NOTE: this aws section is the AWS for the API Server
  # and credentials for the backend only
  aws:
    # Credentials with access to artifact buckets and
    # references/schemas.taskcluster.net if you wish to publish meta-data
    accessKeyId: !env AWS_ACCESS_KEY_ID
    secretAccessKey: !env AWS_SECRET_ACCESS_KEY
    region: us-west-2
    apiVersion: 2014-01-01

# Configuration in production
production:
  sqsSimple:
    queueName: cloud-mirror-production
  taskcluster:
    authBaseUrl: https://auth.taskcluster.net/v1
  server:
    publicUrl: https://cloud-mirror.taskcluster.net
    env: production
    forceSSL: true
    ensureSSL: true
    trustProxy: true

development:
  backend:
    count: 1
  sqsSimple:
    queueName: cloud-mirror-development
  app:
    ensureSSL: false
    maxWaitForCachedCopy: 100000 #ms
    allowedPatterns:
      - '^.*/'
  redis:
    host: 127.0.0.1
  monitoring:
    enable: false
  server:
    port: 5555
    env: development
    publicUrl: http://localhost:5555
test:
  sqsSimple:
    queueName: cloud-mirror-test
  backend:
    count: 10
    s3:
      regions: 'us-west-1'
  app:
    ensureSSL: true
    maxWaitForCachedCopy: 5000 #ms
    allowedPatterns:
      - '^https://httpbin.org/'
      - '^https://taskcluster-httpbin.herokuapp.com/'
      - '^https://www.google.com/'
      - '^https://google.com/'
      - '^http://www.google.com/'
  redis:
    host: 127.0.0.1
  monitoring:
    enable: false
  server:
    port: 5556
    env: development
    publicUrl: http://localhost:5556
